#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# Core server cookbooks
cookbook 'locale',
  git: 'https://github.com/hw-cookbooks/locale'
cookbook 'apt'
cookbook 'sudo'
cookbook 'build-essential'
cookbook 'git', 
  git: 'https://github.com/fnichol/chef-git.git'
cookbook 'imagemagick'
cookbook 'user'

# App server cookbooks
cookbook 'rvm',
  :git => 'https://github.com/martinisoft/chef-rvm',
  :ref => "v0.9.2"

# DB server cookbooks
# cookbook 'postgresql', github: "phlipper/chef-postgresql"
cookbook 'mysql', "5.6.1"

# Web and App server cookbooks
cookbook 'nginx'

cookbook 'nodejs'
# cookbook 'npm',
#   git: 'https://github.com/soofaloofa/chef-npm-package-install'

# Solr search server
# cookbook 'solr', '~> 0.3.0'

# Redis server
cookbook 'redisio'
